# Generated by Django 3.2.12 on 2022-03-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0002_auto_20220306_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-pk']},
        ),
    ]
